flowchart LR
    plumage[["`plumage`"]]

    subgraph primary-deps [Primary dependencies]
        pelican_myst_reader{{"`pelican-myst-reader`"}}
        pelican_webassets{{"`pelican-webassets`"}}
        pelican{{"`pelican`"}}
        pyquery{{"`pyquery`"}}
        pygments{{"`pygments`"}}
        pyyaml{{"`pyyaml`"}}
        cssmin{{"`cssmin`"}}
        libsass{{"`libsass`"}}
        pynpm{{"`pynpm`"}}
    end

    sphinx(["`sphinx`"])
    myst_parser(["`myst-parser`"])
    docutils(["`docutils`"])
    requests(["`requests`"])
    sphinxcontrib_bibtex(["`sphinxcontrib-bibtex`"])
    jinja2(["`jinja2`"])
    markdown_it_py(["`markdown-it-py`"])
    pybtex(["`pybtex`"])
    anyio(["`anyio`"])
    beautifulsoup4(["`beautifulsoup4`"])
    pybtex_docutils(["`pybtex-docutils`"])
    rich(["`rich`"])
    colorama(["`colorama`"])
    coverage(["`coverage`"])
    feedgenerator(["`feedgenerator`"])
    idna(["`idna`"])
    mdit_py_plugins(["`mdit-py-plugins`"])
    packaging(["`packaging`"])
    pluggy(["`pluggy`"])
    python_dateutil(["`python-dateutil`"])
    typing_extensions(["`typing-extensions`"])
    tzdata(["`tzdata`"])
    watchfiles(["`watchfiles`"])
    alabaster(["`alabaster`"])
    babel(["`babel`"])
    blinker(["`blinker`"])
    certifi(["`certifi`"])
    charset_normalizer(["`charset-normalizer`"])
    cssselect(["`cssselect`"])
    execnet(["`execnet`"])
    imagesize(["`imagesize`"])
    iniconfig(["`iniconfig`"])
    latexcodec(["`latexcodec`"])
    lxml(["`lxml`"])
    markdown_word_count(["`markdown-word-count`"])
    markupsafe(["`markupsafe`"])
    mdurl(["`mdurl`"])
    ordered_set(["`ordered-set`"])
    psutil(["`psutil`"])
    roman_numerals(["`roman-numerals`"])
    six(["`six`"])
    snowballstemmer(["`snowballstemmer`"])
    soupsieve(["`soupsieve`"])
    sphinxcontrib_applehelp(["`sphinxcontrib-applehelp`"])
    sphinxcontrib_devhelp(["`sphinxcontrib-devhelp`"])
    sphinxcontrib_htmlhelp(["`sphinxcontrib-htmlhelp`"])
    sphinxcontrib_jsmath(["`sphinxcontrib-jsmath`"])
    sphinxcontrib_qthelp(["`sphinxcontrib-qthelp`"])
    sphinxcontrib_serializinghtml(["`sphinxcontrib-serializinghtml`"])
    tomli(["`tomli`"])
    unidecode(["`unidecode`"])
    urllib3(["`urllib3`"])

    subgraph grp_test [--group test]
        pytest{{"`pytest >=8.4`"}}
        pytest_cov{{"`pytest-cov >=7`"}}
        pytest_xdist{{"`pytest-xdist >=3.8`"}}
        types_pyyaml{{"`types-pyyaml >=6`"}}
    end

    plumage ==>|" >=4.11 "| pelican
    plumage ==>|" >=1.4 "| pelican_myst_reader
    plumage ==>|" >=2.18 "| pygments
    plumage ==>|" >=6 "| pyyaml
    plumage ==>|" >=2 "| pyquery
    plumage ==>|" >=2 "| pelican_webassets
    plumage ==>|" >=0.2 "| cssmin
    plumage ==>|" >=0.22 "| libsass
    plumage ==>|" >=0.2 "| pynpm
    pelican --> docutils
    pelican --> pygments
    pelican --> jinja2
    pelican --> rich
    pelican --> feedgenerator
    pelican --> python_dateutil
    pelican --> tzdata
    pelican --> watchfiles
    pelican --> blinker
    pelican --> ordered_set
    pelican --> unidecode
    pelican_myst_reader --> pelican
    pelican_myst_reader --> myst_parser
    pelican_myst_reader --> docutils
    pelican_myst_reader --> sphinxcontrib_bibtex
    pelican_myst_reader --> pyyaml
    pelican_myst_reader --> beautifulsoup4
    pelican_myst_reader --> markdown_word_count
    pytest --> pygments
    pytest --> colorama
    pytest --> packaging
    pytest --> pluggy
    pytest --> iniconfig
    pytest_cov --> pytest
    pytest_cov --> coverage
    pytest_cov --> pluggy
    pytest_xdist --> pytest
    pytest_xdist --> execnet
    pytest_xdist --> psutil
    pyquery --> cssselect
    pyquery --> lxml
    pelican_webassets --> pelican
    myst_parser --> sphinx
    myst_parser --> docutils
    myst_parser --> jinja2
    myst_parser --> markdown_it_py
    myst_parser --> pyyaml
    myst_parser --> mdit_py_plugins
    sphinxcontrib_bibtex --> sphinx
    sphinxcontrib_bibtex --> docutils
    sphinxcontrib_bibtex --> pybtex
    sphinxcontrib_bibtex --> pybtex_docutils
    jinja2 --> markupsafe
    beautifulsoup4 --> typing_extensions
    beautifulsoup4 --> soupsieve
    rich --> pygments
    rich --> markdown_it_py
    coverage --> tomli
    feedgenerator --> tzdata
    python_dateutil --> six
    watchfiles --> anyio
    sphinx --> docutils
    sphinx --> pygments
    sphinx --> requests
    sphinx --> jinja2
    sphinx --> colorama
    sphinx --> packaging
    sphinx --> alabaster
    sphinx --> babel
    sphinx --> imagesize
    sphinx --> roman_numerals
    sphinx --> snowballstemmer
    sphinx --> sphinxcontrib_applehelp
    sphinx --> sphinxcontrib_devhelp
    sphinx --> sphinxcontrib_htmlhelp
    sphinx --> sphinxcontrib_jsmath
    sphinx --> sphinxcontrib_qthelp
    sphinx --> sphinxcontrib_serializinghtml
    markdown_it_py --> mdurl
    pybtex --> pyyaml
    pybtex --> latexcodec
    anyio --> idna
    anyio --> typing_extensions
    pybtex_docutils --> docutils
    pybtex_docutils --> pybtex
    mdit_py_plugins --> markdown_it_py
    requests --> idna
    requests --> certifi
    requests --> charset_normalizer
    requests --> urllib3
    plumage -.-> grp_test

    click alabaster "https://pypi.org/project/alabaster/" _blank
    click anyio "https://pypi.org/project/anyio/" _blank
    click babel "https://pypi.org/project/babel/" _blank
    click beautifulsoup4 "https://pypi.org/project/beautifulsoup4/" _blank
    click blinker "https://pypi.org/project/blinker/" _blank
    click certifi "https://pypi.org/project/certifi/" _blank
    click charset_normalizer "https://pypi.org/project/charset-normalizer/" _blank
    click colorama "https://pypi.org/project/colorama/" _blank
    click coverage "https://pypi.org/project/coverage/" _blank
    click cssmin "https://pypi.org/project/cssmin/" _blank
    click cssselect "https://pypi.org/project/cssselect/" _blank
    click docutils "https://pypi.org/project/docutils/" _blank
    click execnet "https://pypi.org/project/execnet/" _blank
    click feedgenerator "https://pypi.org/project/feedgenerator/" _blank
    click idna "https://pypi.org/project/idna/" _blank
    click imagesize "https://pypi.org/project/imagesize/" _blank
    click iniconfig "https://pypi.org/project/iniconfig/" _blank
    click jinja2 "https://pypi.org/project/jinja2/" _blank
    click latexcodec "https://pypi.org/project/latexcodec/" _blank
    click libsass "https://pypi.org/project/libsass/" _blank
    click lxml "https://pypi.org/project/lxml/" _blank
    click markdown_it_py "https://pypi.org/project/markdown-it-py/" _blank
    click markdown_word_count "https://pypi.org/project/markdown-word-count/" _blank
    click markupsafe "https://pypi.org/project/markupsafe/" _blank
    click mdit_py_plugins "https://pypi.org/project/mdit-py-plugins/" _blank
    click mdurl "https://pypi.org/project/mdurl/" _blank
    click myst_parser "https://pypi.org/project/myst-parser/" _blank
    click ordered_set "https://pypi.org/project/ordered-set/" _blank
    click packaging "https://pypi.org/project/packaging/" _blank
    click pelican "https://pypi.org/project/pelican/" _blank
    click pelican_myst_reader "https://pypi.org/project/pelican-myst-reader/" _blank
    click pelican_webassets "https://pypi.org/project/pelican-webassets/" _blank
    click pluggy "https://pypi.org/project/pluggy/" _blank
    click plumage "https://pypi.org/project/plumage/" _blank
    click psutil "https://pypi.org/project/psutil/" _blank
    click pybtex "https://pypi.org/project/pybtex/" _blank
    click pybtex_docutils "https://pypi.org/project/pybtex-docutils/" _blank
    click pygments "https://pypi.org/project/pygments/" _blank
    click pynpm "https://pypi.org/project/pynpm/" _blank
    click pyquery "https://pypi.org/project/pyquery/" _blank
    click pytest "https://pypi.org/project/pytest/" _blank
    click pytest_cov "https://pypi.org/project/pytest-cov/" _blank
    click pytest_xdist "https://pypi.org/project/pytest-xdist/" _blank
    click python_dateutil "https://pypi.org/project/python-dateutil/" _blank
    click pyyaml "https://pypi.org/project/pyyaml/" _blank
    click requests "https://pypi.org/project/requests/" _blank
    click rich "https://pypi.org/project/rich/" _blank
    click roman_numerals "https://pypi.org/project/roman-numerals/" _blank
    click six "https://pypi.org/project/six/" _blank
    click snowballstemmer "https://pypi.org/project/snowballstemmer/" _blank
    click soupsieve "https://pypi.org/project/soupsieve/" _blank
    click sphinx "https://pypi.org/project/sphinx/" _blank
    click sphinxcontrib_applehelp "https://pypi.org/project/sphinxcontrib-applehelp/" _blank
    click sphinxcontrib_bibtex "https://pypi.org/project/sphinxcontrib-bibtex/" _blank
    click sphinxcontrib_devhelp "https://pypi.org/project/sphinxcontrib-devhelp/" _blank
    click sphinxcontrib_htmlhelp "https://pypi.org/project/sphinxcontrib-htmlhelp/" _blank
    click sphinxcontrib_jsmath "https://pypi.org/project/sphinxcontrib-jsmath/" _blank
    click sphinxcontrib_qthelp "https://pypi.org/project/sphinxcontrib-qthelp/" _blank
    click sphinxcontrib_serializinghtml "https://pypi.org/project/sphinxcontrib-serializinghtml/" _blank
    click tomli "https://pypi.org/project/tomli/" _blank
    click types_pyyaml "https://pypi.org/project/types-pyyaml/" _blank
    click typing_extensions "https://pypi.org/project/typing-extensions/" _blank
    click tzdata "https://pypi.org/project/tzdata/" _blank
    click unidecode "https://pypi.org/project/unidecode/" _blank
    click urllib3 "https://pypi.org/project/urllib3/" _blank
    click watchfiles "https://pypi.org/project/watchfiles/" _blank

    style plumage stroke-width:3px
    style cssmin stroke-width:3px
    style libsass stroke-width:3px
    style pelican stroke-width:3px
    style pelican_myst_reader stroke-width:3px
    style pelican_webassets stroke-width:3px
    style pygments stroke-width:3px
    style pynpm stroke-width:3px
    style pyquery stroke-width:3px
    style pytest stroke-width:3px
    style pytest_cov stroke-width:3px
    style pytest_xdist stroke-width:3px
    style pyyaml stroke-width:3px
    style types_pyyaml stroke-width:3px

    style primary-deps fill:#1565C020,stroke:#42A5F5
    style grp_test fill:#546E7A20,stroke:#90A4AE
