---
name: Autofix
"on":
  push:
    # Only targets main branch to avoid amplification effects of auto-fixing
    # the exact same stuff in multiple non-rebased branches.
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/workflows/.github/workflows/autofix.yaml@v4.3.4
    with:
      gitignore-extra-categories: node

  pygments-styles:
    name: Generate Pygment styles
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install -r https://raw.githubusercontent.com/kdeldycke/workflows/v4.3.1/requirements/uv.txt
      - name: Install Pygments
        run: |
          uv --no-progress venv --system
          uv --no-progress pip install .
      - name: Generate Pygments styles
        run: |
          for STYLE in $( uv --no-progress run -- pygmentize -L styles --json | jq -r '.["styles"] | keys[]' );
          do
            CSS_FILE="./plumage/static/css/pygments/$STYLE.css"
            uv --no-progress run -- pygmentize -f html -S "$STYLE" -a ".highlight" > "$CSS_FILE"
          done
      - uses: peter-evans/create-pull-request@v6.1.0
        with:
          assignees: ${{ github.actor }}
          commit-message: "[autofix] Update Pygments styles"
          title: "[autofix] Update Pygments styles"
          body: >
            <details><summary><code>Workflow metadata</code></summary>


            > [Auto-generated on run `#${{ github.run_id }}`](${{ github.event.repository.html_url }}/actions/runs/${{
            github.run_id }}) by `${{ github.job }}` job from [`autofix.yaml`](${{ github.event.repository.html_url
            }}/blob/${{ github.sha }}/.github/workflows/autofix.yaml) workflow.


            </details>
          labels: "📦 dependencies"
          branch: update-pygments-styles
          add-paths: |
            plumage/static/css/pygments/*.css

  format-css:
    name: Format CSS files and create a PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install npm
        run: |
          sudo apt --quiet --yes install npm
      - name: Install stylelint
        run: |
          npm install --save-dev stylelint stylelint-config-standard stylelint-config-sass-guidelines
      - name: Autofix CSS
        # Allow that step to fail so we can proceed with creating the auto-fix PR below.
        run: |
          npx stylelint --fix --config stylelint-config-standard "plumage/static/**/*.css" || true
          npx stylelint --fix --config stylelint-config-sass-guidelines "plumage/static/**/*.scss" || true
      - uses: peter-evans/create-pull-request@v6.1.0
        with:
          assignees: ${{ github.actor }}
          commit-message: "[autofix] Format CSS style"
          title: "[autofix] Format CSS style"
          body: >
            <details><summary><code>Workflow metadata</code></summary>


            > [Auto-generated on run `#${{ github.run_id }}`](${{ github.event.repository.html_url }}/actions/runs/${{
            github.run_id }}) by `${{ github.job }}` job from [`autofix.yaml`](${{ github.event.repository.html_url
            }}/blob/${{ github.sha }}/.github/workflows/autofix.yaml) workflow.


            </details>
          labels: "🤖 ci"
          branch: autofix-css
          # Only commit css and scss files at any depth of the plumage/static/ subtree.
          add-paths: |
            plumage/static/*.css
            plumage/static/*.scss

  format-jinja:
    name: Format Jinja
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          python -m pip install -r https://raw.githubusercontent.com/kdeldycke/workflows/v4.3.1/requirements/uv.txt
      - name: Install djlint
        run: |
          uv --no-progress venv --system
          uv --no-progress pip install ".[test]"
      - name: Autofix Jinja
        run: >
          uv --no-progress run -- djlint
          --reformat
          --profile jinja
          --format-css
          --format-js
          --warn
          plumage/templates/*.html
      - uses: peter-evans/create-pull-request@v6.1.0
        with:
          assignees: ${{ github.actor }}
          commit-message: "[autofix] Format Jinja"
          title: "[autofix] Format Jinja"
          body: >
            <details><summary><code>Workflow metadata</code></summary>


            > [Auto-generated on run `#${{ github.run_id }}`](${{ github.event.repository.html_url }}/actions/runs/${{
            github.run_id }}) by `${{ github.job }}` job from [`autofix.yaml`](${{ github.event.repository.html_url
            }}/blob/${{ github.sha }}/.github/workflows/autofix.yaml) workflow.


            </details>
          labels: "🤖 ci"
          branch: autofix-jinja