---
name: Changelog & versions
"on":
  push:
    branches:
      - main
    paths:
      - changelog.md
      - .bumpversion.cfg
      - .github/workflows/changelog.yaml
      - .github/workflows/release.yaml

jobs:

  changelog:
    uses: kdeldycke/workflows/.github/workflows/changelog.yaml@v2.17.3
